---
title: My Visualizations
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: your.name@gmail.com
brand: Your Name
headline: Inventor, Engineer and Futurist
description: 'New Site

'
baseurl: 
url: http://example.com
copyright: 2016 Whatever Company, Inc. All Rights Reserved.
markdown: kramdown
snapwidget: 247552
phone: "+1-800-555-2016"
googleAnalitycsID: UA-83933844-1
